"""propagate_doctor_customid_relations

Revision ID: 128568efe5d5
Revises: 413d0005da33
Create Date: 2026-05-06 02:05:50.946149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '128568efe5d5'
down_revision: Union[str, Sequence[str], None] = '413d0005da33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # 1. Add columns as nullable first
    op.add_column('doctor_profiles', sa.Column('custom_id', sa.String(), nullable=True))
    op.add_column('doctor_profiles', sa.Column('mobile', sa.String(), nullable=True))
    
    # 2. Populate custom_id for existing rows
    # We use a placeholder '00000-' + full_name
    op.execute("UPDATE doctor_profiles SET custom_id = '00000-' || UPPER(full_name)")
    
    # 3. Now make custom_id NOT NULL and add constraints
    op.alter_column('doctor_profiles', 'custom_id', nullable=False)
    op.create_unique_constraint(None, 'doctor_profiles', ['mobile'])
    op.drop_column('doctor_profiles', 'id')
    op.create_primary_key('doctor_profiles_pkey', 'doctor_profiles', ['custom_id'])
    
    # 4. Update Slot table
    op.alter_column('slots', 'doctor_id',
               existing_type=sa.UUID(),
               type_=sa.String(),
               existing_nullable=False)
    
    # We need to update doctor_id in slots to match the new custom_id
    # This is tricky because we don't know which UUID belongs to which custom_id in SQL without a join
    op.execute("""
        UPDATE slots 
        SET doctor_id = dp.custom_id 
        FROM doctor_profiles dp 
        WHERE slots.doctor_id::uuid = dp.user_id
    """)
    
    op.create_foreign_key(None, 'slots', 'doctor_profiles', ['doctor_id'], ['custom_id'])


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'slots', type_='foreignkey')
    op.alter_column('slots', 'doctor_id',
               existing_type=sa.String(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.add_column('doctor_profiles', sa.Column('id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'doctor_profiles', type_='unique')
    op.drop_column('doctor_profiles', 'mobile')
    op.drop_column('doctor_profiles', 'custom_id')
    # ### end Alembic commands ###
