"""add_fullname_mobile_customid_to_patient

Revision ID: 1941de098110
Revises: phase3_clinical
Create Date: 2026-05-06 01:27:07.071570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1941de098110'
down_revision: Union[str, Sequence[str], None] = 'phase3_clinical'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patient_profiles', sa.Column('mobile', sa.String(), nullable=True))
    op.add_column('patient_profiles', sa.Column('custom_id', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'patient_profiles', ['custom_id'])
    op.create_unique_constraint(None, 'patient_profiles', ['mobile'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'patient_profiles', type_='unique')
    op.drop_constraint(None, 'patient_profiles', type_='unique')
    op.drop_column('patient_profiles', 'custom_id')
    op.drop_column('patient_profiles', 'mobile')
    # ### end Alembic commands ###
