"""propagate_patient_customid_relations

Revision ID: 413d0005da33
Revises: a2db6dc3732c
Create Date: 2026-05-06 01:34:23.981979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '413d0005da33'
down_revision: Union[str, Sequence[str], None] = 'a2db6dc3732c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('appointments', 'patient_id',
               existing_type=sa.UUID(),
               type_=sa.String(),
               existing_nullable=False)
    op.create_foreign_key(None, 'appointments', 'patient_profiles', ['patient_id'], ['custom_id'])
    op.alter_column('medical_records', 'patient_id',
               existing_type=sa.UUID(),
               type_=sa.String(),
               existing_nullable=False)
    op.create_foreign_key(None, 'medical_records', 'patient_profiles', ['patient_id'], ['custom_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'medical_records', type_='foreignkey')
    op.alter_column('medical_records', 'patient_id',
               existing_type=sa.String(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.alter_column('appointments', 'patient_id',
               existing_type=sa.String(),
               type_=sa.UUID(),
               existing_nullable=False)
    # ### end Alembic commands ###
