"""add_appointment_status_timestamp

Revision ID: 563b4e728893
Revises: 6d2bcb5e90ed
Create Date: 2026-05-06 06:03:46.675663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '563b4e728893'
down_revision: Union[str, Sequence[str], None] = '6d2bcb5e90ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('status_changed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appointments', 'status_changed_at')
    # ### end Alembic commands ###
