"""add_email_to_profiles

Revision ID: 5e44b81d64f0
Revises: 74ac43c61de4
Create Date: 2026-05-06 07:14:28.735557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e44b81d64f0'
down_revision: Union[str, Sequence[str], None] = '74ac43c61de4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctor_profiles', sa.Column('email', sa.String(), nullable=True))
    op.add_column('patient_profiles', sa.Column('email', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patient_profiles', 'email')
    op.drop_column('doctor_profiles', 'email')
    # ### end Alembic commands ###
