"""add_unique_constraint_to_slots

Revision ID: 6c6756f160b9
Revises: fbe75e476eed
Create Date: 2026-05-06 05:30:14.242590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c6756f160b9'
down_revision: Union[str, Sequence[str], None] = 'fbe75e476eed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uix_doctor_slot_time', 'slots', ['doctor_id', 'start_time'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_doctor_slot_time', 'slots', type_='unique')
    # ### end Alembic commands ###
