"""add_source_and_created_at_to_appointment

Revision ID: 74ac43c61de4
Revises: 4b7d27ea8925
Create Date: 2026-05-06 06:58:09.560666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74ac43c61de4'
down_revision: Union[str, Sequence[str], None] = '4b7d27ea8925'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('source', sa.String(), nullable=True))
    op.add_column('appointments', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appointments', 'created_at')
    op.drop_column('appointments', 'source')
    # ### end Alembic commands ###
