"""change_patient_pk_to_customid

Revision ID: a2db6dc3732c
Revises: 1941de098110
Create Date: 2026-05-06 01:29:48.961871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2db6dc3732c'
down_revision: Union[str, Sequence[str], None] = '1941de098110'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('patient_profiles', 'custom_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint('patient_profiles_custom_id_key', 'patient_profiles', type_='unique')
    # Drop the old primary key on 'id' and add the new one on 'custom_id'
    op.drop_column('patient_profiles', 'id')
    op.create_primary_key('patient_profiles_pkey', 'patient_profiles', ['custom_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patient_profiles', sa.Column('id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('patient_profiles_custom_id_key'), 'patient_profiles', ['custom_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('patient_profiles', 'custom_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
