"""add_rating_and_feedback

Revision ID: e073ca3fda92
Revises: 563b4e728893
Create Date: 2026-05-06 06:30:16.038179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e073ca3fda92'
down_revision: Union[str, Sequence[str], None] = '563b4e728893'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('rating', sa.Integer(), nullable=True))
    op.add_column('appointments', sa.Column('feedback', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appointments', 'feedback')
    op.drop_column('appointments', 'rating')
    # ### end Alembic commands ###
